
ignore = [
  # ruff/black auto-formats lines, trust it
  "E501",
]

select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    #"UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
target-version = "py39"
# Ignore files not refactored yet
exclude = ["NASASRTMUtil.py", "configUtil.py"]


# Same as black
line-length = 88

[lint.isort]
known-first-party = ["pyhgtmap"]
