name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: sdist + pure wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Install latest pip, hatch
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade hatch

      - name: Build wheel and source distributions
        run: hatch build

      - name: Upload to PyPI
        run: hatch publish -u __token__
        env:
          HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
